#Read and Writing Data in Text Format

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('ex1.csv') #sep=','
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [39]:
pd.read_csv('ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [40]:
pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message']) #names dùng cho bảng sẵn, columns dùng khi tự tạo

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [41]:
pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'],index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [42]:
#hierarchical index
parsed = pd.read_csv('csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [43]:
result = pd.read_table('ex3.txt', sep='\s+') # \s+ ngăn cách bằng 1 chuỗi dấu cách liền kề, mặc định của read_table là tab (\t)
result

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\d3s1g\AppData\Local\Temp\ipykernel_14684\2543860691.py:1: SyntaxWarning: invalid escape sequence '\s'
  result = pd.read_table('ex3.txt', sep='\s+') # \s+ ngăn cách bằng 1 chuỗi dấu cách liền kề, mặc định của read_table là tab (\t)

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [44]:
pd.read_csv('ex4.csv', skiprows=[0, 2, 3]) #trong file có 3 dòng comment nếu pandas đọc thì sẽ lỗi
#có thể dùng ", comment='#'" thay vì skiprows

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [45]:
result = pd.read_csv('ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [46]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [47]:
#How to show rows which having at least one null value :

result[result.isna().sum(axis=1) > 0]
#hoặc
result[result.isna().any(axis=1)]

  something  a  b    c  d message
0       one  1  2  3.0  4     NaN
1       two  5  6  NaN  8   world

In [48]:
#Set NA sentinels
sentinels = {'message': ['foo'], 'something': ['two']}
pd.read_csv('ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [49]:
import numpy as np

a = np.random.rand(10000,4)
a

key = np.array(['L','B','G','R','Q','H','E'])
b = np.random.randint(0,6,(10000,))

with open("ex6.txt","w") as f:
  for i in range(len(b)):
    f.write('\t'.join(["%.2f" % number for number in a[i]]) + '\t' + key[b][i]+"\n")

In [50]:
pd.read_csv('ex6.csv', nrows=5, sep="\t")

    one   two  three  four key
0  0.74  0.03   0.35  0.28   H
1  0.75  0.81   0.85  0.56   R
2  0.42  0.39   0.48  0.98   H
3  0.18  0.72   0.93  0.15   Q
4  0.71  0.83   0.22  0.46   L

In [51]:
chunker = pd.read_csv('ex6.csv', chunksize=1000,sep="\t")
chunker

In [52]:
tot = pd.Series([])
for piece in chunker:
  tot = tot.add(piece['key'].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot

key
L    1731
G    1691
R    1687
Q    1668
H    1653
B    1570
dtype: object

#Writing Data to Text Format

In [53]:
data = pd.read_csv('ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [54]:
data.to_csv('out.csv',sep=',')

In [55]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [56]:
data.to_csv('out.csv',sep=',',na_rep='NA')

In [57]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,NA
1,two,5,6,NA,8,world
2,three,9,10,11.0,12,foo

In [58]:
data.to_csv('out.csv', index=False, columns=['a', 'b', 'c'])
!cat out.csv
pd.read_csv('out.csv', sep=",")

a,b,c
1,2,3.0
5,6,
9,10,11.0

   a   b     c
0  1   2   3.0
1  5   6   NaN
2  9  10  11.0

#Json data

In [59]:
obj = """
    {"name": "Wes",
     "places_lived": ["United States", "Spain", "Germany"],
     "pet": null,
     "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
                  {"name": "Katie", "age": 38,
                   "pets": ["Sixes", "Stache", "Cisco"]}]
} """

In [60]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [61]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [62]:
data = pd.read_json('example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [63]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [64]:
print(data.to_json(orient='records')) #Dữ liệu được tổ chức theo từng hàng

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

#Pickle

To export data in binary format

In [65]:
frame = pd.read_csv('ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [66]:
frame.to_pickle('frame_pickle')

In [67]:
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#Microsoft Excel Files

In [68]:
xlsx = pd.ExcelFile('ex1.xlsx')
pd.read_excel(xlsx, 'sheet1')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [69]:
pd.read_excel('ex1.xlsx', 'sheet1')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [74]:
frame.to_excel('ex2.xlsx',sheet_name='sheet1', index=False)
pd.read_excel('ex2.xlsx')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo